export interface SeasonPass {
    attempts: string | null,
    completions: string | null,
    pass_yards: number | null,
    pass_yards_after_catch: number | null,
    pass_air_yards: number | null,
    pass_air_conversion_ratio: number | null,
    dakota: number | null,
    pass_epa: number | null,
    pass_tds: string | null,
    pass_two_pt_conversions: string | null,
    interceptions: string | null,
    sacks: number | null,
    sack_yards: number | null,
    sack_fumbles: string | null,
    sack_fumbles_lost: string | null,
}