export interface SeasonRec {
    targets: number | null,
    receptions: number | null,
    target_share: number | null,
    rec_yards: number | null,
    rec_yards_after_catch: number | null,
    rec_air_yards: number | null,
    rec_air_yards_share: number | null,
    rec_air_conversion_ratio: number | null,
    weighted_opportunity_rating: number | null,
    rec_epa: number | null,
    rec_tds: number | null,
    rec_two_pt_conversions: number | null,
    rec_first_downs: number | null,
    rec_fumbles: number | null,
    rec_fumbles_lost: number | null,
}