export interface SeasonRec {
    targets: string | null,
    receptions: string | null,
    target_share: number | null,
    rec_yards: number | null,
    rec_yards_after_catch: number | null,
    rec_air_yards: number | null,
    rec_air_yards_share: number | null,
    rec_air_conversion_ratio: number | null,
    weighted_opportunity_rating: number | null,
    rec_epa: number | null,
    rec_tds: string | null,
    rec_two_pt_conversions: string | null,
    rec_first_downs: string | null,
    rec_fumbles: string | null,
    rec_fumbles_lost: string | null,
}