import { WeekData } from "@interfaces/models/week/week";

export enum StatCategoryLabel {
    Advanced = 'advanced',
    NextGen = 'nextgen',
    Stats = 'stats',
} 

export enum StatTypeLabel {
    Pass = 'pass',
    Rec = 'rec',
    Rush = 'rush',
} 

export enum StatLabel {
    Attempts = 'attempts',
    Carries = "carries",
    Completions = 'completions',
    PassAggressive = 'aggressiveness',
    PassAirConvRatio = 'pass_air_conversion_ratio',
    PassAirYards = 'pass_air_yards',
    PassAvgAirYards = 'avg_air_distance',    
    PassAvgAirYardsCompleted = 'avg_completed_air_yards',
    PassAvgAirYardsIntended = 'avg_intended_air_yards',
    PassAvgAirYardsToSticks = 'avg_air_yards_to_sticks',
    PassAvgTimeToThrow = 'avg_time_to_throw',
    PassBadThrowPct = 'bad_throw_pct',
    PassBadThrows = 'bad_throws',    
    PassBlitzed = 'blitzed',
    PassCompletionPct = 'completion_pct',
    PassCompletionsAboveExpected = 'completions_above_expectation_pct',
    PassCompletionsExpectedPct = 'expected_completion_pct',    
    PassDakota = 'dakota',
    PassDropPct = 'pass_drop_pct',
    PassDrops = 'pass_drops',
    PassEPA = 'pass_epa',
    PassHit = 'hit',
    PassHurried = 'hurried',
    PassInterceptions = 'interceptions',
    PassMaxAirYardsCompleted = 'max_air_distance',
    PassMaxAirYardsIntended = 'max_completed_air_distance',
    PassQBR = 'passer_rating',
    PassPressured = 'pressured',
    PassPressuredPct = 'pressured_pct',
    PassTDs = 'pass_tds',
    PassYAC = 'pass_yards_after_catch',
    PassYards = 'pass_yards',
    RecAirConvRatio = 'rec_air_conversion_ratio',
    RecAvgCushion = 'avg_cushion',
    RecExpectedYAC = 'avg_expected_yac',
    RecAvgSeparation = 'avg_separation',
    RecAirYards = 'rec_air_yards',
    RecAvgIntendedAirYards = 'avg_intended_air_yards',
    RecCatchPct = 'catch_pct',
    RecDrops = 'drops',
    RecIntendedAirYardsShare = 'share_of_intended_air_yards_pct',
    RecEPA = 'rec_epa',
    RecQBR = 'qb_rating',
    RecTDs = 'rec_tds',
    RecYards = 'rec_yards',
    RecYAC = 'rec_yards_after_catch',
    Receptions = 'receptions',
    Rush8Box = 'attempts_gte_eight_defenders_pct',
    RushAvgYAC = 'yards_after_contact_avg',
    RushAvgYBC = 'yards_before_contact_avg',
    RushEfficiency = 'efficiency',
    RushEPA = 'rush_epa',
    RushLoS = 'avg_time_to_los',
    RushTDs = 'rush_tds',
    RushYAC = 'yards_after_contact',
    RushYBC = 'yards_before_contact',
    RushYards = 'rush_yards',
    RushYPC = 'avg_yards',
    RecTargets = 'targets',
    RecTargetShare = 'target_share',
    Sacks = 'sacks',
} 

export enum PlayerStatsTypes {
    Passing,
    Receiving,
    Rushing
}

export enum PlayerStats {
    Attempts,
    Carries,
    Completions,
    PassAggressive,
    PassAirConvRatio,
    PassAirYards,
    PassAvgAirYards,
    PassAvgAirYardsCompleted,
    PassAvgAirYardsIntended,
    PassAvgAirYardsToSticks,
    PassAvgTimeToThrow,
    PassBadThrowPct,
    PassBadThrows,
    PassBlitzed,
    PassCompletionPct,
    PassCompletionsAboveExpected,
    PassCompletionsExpectedPct,
    PassDakota,
    PassDropPct,
    PassDrops,
    PassEPA,
    PassHit,
    PassHurried,
    PassInterceptions,
    PassMaxAirYardsCompleted,
    PassMaxAirYardsIntended,
    PassQBR,
    PassPressured,
    PassPressuredPct,
    PassTDs,
    PassYAC,
    PassYards,
    RecACR,
    RecAvgCushion,
    RecAvgExpectedYAC,
    RecAvgSeperation,
    RecAirYards,
    RecCatchPercentage,
    RecIntendedAirYards,
    RecIntendedAirYardsShare,
    RecDrops,
    RecEPA,
    RecQBR,
    RecTDs,
    RecYards,
    RecYAC,
    Receptions,
    Rush8Box,
    RushAvgYAC,
    RushAvgYBC,
    RushEfficiency,
    RushEPA,
    RushLoS,
    RushTDs,
    RushYAC,
    RushYBC,
    RushYards,
    RushYPC,
    Sacks,
    Targets,
    TargetShare,
}

export enum PlayerStatLabels {
    Attempts = "Attempts",
    Carries = "Carries",
    Completions = "Completions",
    PassAggressive = "Aggressiveness",
    PassAirConvRatio = "Air Conversion Ratio",
    PassAirYards = "Air Yards",
    PassAvgAirYards = "Average Air Yards",
    PassAvgAirYardsCompleted = "Average Air Yards (Completed)",
    PassAvgAirYardsIntended = "Avgerage Air Yards (Intended)",
    PassAvgAirYardsToSticks = "Average Air Yards (To Sticks))",
    PassAvgTimeToThrow = "Average Time to Throw",
    PassBadThrowPct = "Bad Throw Percentage",
    PassBadThrows = "Bad Throws",
    PassBlitzed = "Times Blized",
    PassCompletionPct = "Completion Percentage",
    PassCompletionsAboveExpected = "Completions Above Expected",
    PassCompletionsExpectedPct = "Completions Expected",
    PassDakota = "Dakota",    
    PassDropPct = "Drop Percentage",
    PassDrops = "Drops",
    PassEPA = "EPA",
    PassHit = "Times Hit",
    PassHurried = "Times Hurried",
    PassInterceptions = "Interceptions",
    PassMaxAirYardsCompleted = "Deepest Completeion",
    PassMaxAirYardsIntended = "Deepest Target",
    PassQBR = "QBR",
    PassPressured = "Times Pressured",
    PassPressuredPct = "Pressured Percentage",
    PassTDs = "Touchdowns",
    PassYAC = "Yards After Catch",
    PassYards = "Yards",
    RecACR = 'Air Conversion Ratio',
    RecAvgCushion = 'Average Cushion',
    RecAvgExpectedYAC = 'Average Expected YAC',
    RecAvgSeperation = 'Average Separation',
    RecAirYards = 'Air Yards',
    RecCatchPercentage = 'Catch Percentage',
    RecIntendedAirYards = 'Intended Air Yards',
    RecIntendedAirYardsShare = 'Share of Intended Air Yards',
    RecDrops = 'Drops',
    RecEPA = 'EPA',
    RecQBR = 'QBR When Targeted',
    RecTDs = 'Receiving Touchdowns',
    RecWOR = 'Weighted Opportunity Share',
    RecYards = 'Yards',
    RecYAC = 'Yards After Catch',
    Receptions = 'Receptions',
    Rush8Box = '8+ Box',
    RushAvgYAC = 'Average Yard After Contact',
    RushAvgYBC = 'Average Yard Before Contact',
    RushEfficiency = 'Efficiency',
    RushEPA = 'EPA',
    RushLoS = 'Time to Line of Scrimmage',
    RushTDs = 'Rushing Touchdowns',
    RushYAC = 'Yards After Contact',
    RushYBC = 'Yards Before Contact',
    RushYards = 'Yards',
    RushYPC = 'Yards Per Carry',
    Sacks = "Sacks",
    Targets = 'Targets',
    TargetShare = 'Target Share',
}



